
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.1
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.1",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.OrganisationScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  type: 'type',
  tier: 'tier',
  onboardingMode: 'onboardingMode',
  mfaRequired: 'mfaRequired',
  trialEndsAt: 'trialEndsAt',
  isSandbox: 'isSandbox',
  scimEnabled: 'scimEnabled',
  scimApiKey: 'scimApiKey',
  dataResidency: 'dataResidency',
  isActive: 'isActive',
  metadata: 'metadata',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  emailVerified: 'emailVerified',
  emailVerifiedAt: 'emailVerifiedAt',
  passwordHash: 'passwordHash',
  firstName: 'firstName',
  lastName: 'lastName',
  orgId: 'orgId',
  roles: 'roles',
  tier: 'tier',
  mfaEnabled: 'mfaEnabled',
  mfaSecret: 'mfaSecret',
  mfaEnabledAt: 'mfaEnabledAt',
  lastLoginAt: 'lastLoginAt',
  lastLoginIp: 'lastLoginIp',
  failedLoginAttempts: 'failedLoginAttempts',
  lockedUntil: 'lockedUntil',
  provider: 'provider',
  providerId: 'providerId',
  externalId: 'externalId',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RefreshTokenScalarFieldEnum = {
  id: 'id',
  tokenHash: 'tokenHash',
  family: 'family',
  userId: 'userId',
  orgId: 'orgId',
  deviceId: 'deviceId',
  userAgent: 'userAgent',
  ipAddress: 'ipAddress',
  expiresAt: 'expiresAt',
  revokedAt: 'revokedAt',
  usedAt: 'usedAt',
  createdAt: 'createdAt'
};

exports.Prisma.EmailVerificationTokenScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  tokenHash: 'tokenHash',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt'
};

exports.Prisma.PasswordResetTokenScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  tokenHash: 'tokenHash',
  expiresAt: 'expiresAt',
  usedAt: 'usedAt',
  createdAt: 'createdAt'
};

exports.Prisma.MFABackupCodeScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  codeHash: 'codeHash',
  usedAt: 'usedAt',
  createdAt: 'createdAt'
};

exports.Prisma.InviteScalarFieldEnum = {
  id: 'id',
  orgId: 'orgId',
  email: 'email',
  role: 'role',
  invitedBy: 'invitedBy',
  tokenHash: 'tokenHash',
  expiresAt: 'expiresAt',
  acceptedAt: 'acceptedAt',
  createdAt: 'createdAt'
};

exports.Prisma.SSOConfigScalarFieldEnum = {
  id: 'id',
  orgId: 'orgId',
  protocol: 'protocol',
  entryPoint: 'entryPoint',
  cert: 'cert',
  issuer: 'issuer',
  discoveryUrl: 'discoveryUrl',
  clientId: 'clientId',
  clientSecret: 'clientSecret',
  scopes: 'scopes',
  attributeMap: 'attributeMap',
  isActive: 'isActive',
  createdAt: 'createdAt'
};

exports.Prisma.AuditEventScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  orgId: 'orgId',
  orgSlug: 'orgSlug',
  action: 'action',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  deviceId: 'deviceId',
  result: 'result',
  metadata: 'metadata',
  createdAt: 'createdAt'
};

exports.Prisma.DepartmentScalarFieldEnum = {
  id: 'id',
  orgId: 'orgId',
  name: 'name',
  code: 'code',
  headOfDepartment: 'headOfDepartment',
  parentDepartmentId: 'parentDepartmentId'
};

exports.Prisma.WorkspaceScalarFieldEnum = {
  id: 'id',
  orgId: 'orgId',
  departmentId: 'departmentId',
  name: 'name',
  jurisdictionProfile: 'jurisdictionProfile'
};

exports.Prisma.PermissionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  orgId: 'orgId',
  resource: 'resource',
  action: 'action',
  conditions: 'conditions',
  grantedBy: 'grantedBy',
  expiresAt: 'expiresAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.OrgType = exports.$Enums.OrgType = {
  LAW_FIRM: 'LAW_FIRM',
  CORPORATE: 'CORPORATE',
  GOVERNMENT: 'GOVERNMENT',
  SOLO: 'SOLO',
  ACADEMIC: 'ACADEMIC'
};

exports.OrgTier = exports.$Enums.OrgTier = {
  FREE: 'FREE',
  EDGE: 'EDGE',
  VERTEX: 'VERTEX',
  ZENITH: 'ZENITH'
};

exports.OnboardingMode = exports.$Enums.OnboardingMode = {
  SELF_SERVE: 'SELF_SERVE',
  INVITE_ONLY: 'INVITE_ONLY',
  ENTERPRISE_SSO: 'ENTERPRISE_SSO'
};

exports.UserTier = exports.$Enums.UserTier = {
  LEARN: 'LEARN',
  EDGE: 'EDGE',
  VERTEX: 'VERTEX',
  ZENITH: 'ZENITH'
};

exports.AuthProvider = exports.$Enums.AuthProvider = {
  LOCAL: 'LOCAL',
  GOOGLE: 'GOOGLE',
  MICROSOFT: 'MICROSOFT',
  SAML: 'SAML',
  OIDC: 'OIDC',
  SCIM: 'SCIM'
};

exports.Role = exports.$Enums.Role = {
  ORG_ADMIN: 'ORG_ADMIN',
  WORKSPACE_ADMIN: 'WORKSPACE_ADMIN',
  PARTNER: 'PARTNER',
  FEE_EARNER: 'FEE_EARNER',
  PARALEGAL: 'PARALEGAL',
  CLIENT: 'CLIENT',
  EXTERNAL_REVIEWER: 'EXTERNAL_REVIEWER',
  BILLING_MANAGER: 'BILLING_MANAGER',
  READ_ONLY: 'READ_ONLY',
  API_CONSUMER: 'API_CONSUMER'
};

exports.SSOProtocol = exports.$Enums.SSOProtocol = {
  SAML: 'SAML',
  OIDC: 'OIDC'
};

exports.Prisma.ModelName = {
  Organisation: 'Organisation',
  User: 'User',
  RefreshToken: 'RefreshToken',
  EmailVerificationToken: 'EmailVerificationToken',
  PasswordResetToken: 'PasswordResetToken',
  MFABackupCode: 'MFABackupCode',
  Invite: 'Invite',
  SSOConfig: 'SSOConfig',
  AuditEvent: 'AuditEvent',
  Department: 'Department',
  Workspace: 'Workspace',
  Permission: 'Permission'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
